---
framework: jest
# blocklist:
#   - "test/algorithms/geometric-test.js##Parent suite##new test suite updated geometric algorithm"
#   - "test/algorithms/geometric-test.js##Parent suite##geometric algorithm"
preRun:
     command:
        - npm i
preMerge:
  pattern:
    - "test/algorithms/geometric-test.js"
    - "test/algorithms/new-test.js"
postMerge: 
  pattern: 
    - "test/algorithms/geometric-test.js"
    - "test/algorithms/new-test.js"
postRun:
     command:
        - node --version
nodeVersion: 14.18.1
parallelism: 3
version: 1.0
