---
framework: jest
tier: large
blocklist:
  - "test/algorithms/geometric-test.js##new test suite updated geometric algorithm##should have inverse functions for getPosition and getValue"
  - "test/algorithms/geometric-test.js##geometric algorithm##should handle the minimum end of the range correctly"
  - "test/algorithms/new-test.js##New algorithm##should have inverse functions for getPosition and getValue"
postMerge: 
  pattern: 
    - "test/algorithms/geometric-test.js"
    - "test/algorithms/new-test.js"
preMerge:
  pattern:
    - "test/algorithms/geometric-test.js"
    - "test/algorithms/new-test.js"
preRun:
     command:
        - npm i
postRun:
     command:
        - node --version
version: 1.0
