---
framework: jest
# blocklist:
#   - "test/algorithms/geometric-test.js##new geometric algorithm##internal new geometric algorithm"
postMerge: 
  pattern: 
    - "test/algorithms/geometric-test.js"
  strategy: 
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "test/algorithms/geometric-test.js"
preRun:
     command:
        - npm i
postRun:
     command:
        - node --version
version: 2.1
