---
framework: jest
tier: large
blocklist:
  - "test/algorithms/geometric-test.js##Parent suite##new test suite updated geometric algorithm"
  - "test/algorithms/geometric-test.js##Parent suite##geometric algorithm"
postMerge: 
  pattern: 
    - "test/algorithms/geometric-test.js"
    - "test/algorithms/new-test.js"
preMerge:
  pattern:
    - "test/algorithms/geometric-test.js"
    - "test/algorithms/new-test.js"
preRun:
     command:
        - npm i
postRun:
     command:
        - node --version
version: 1.0