---
framework: jest
tier: large
# blocklist:
#   - "test/algorithms/geometric-test.js##new geometric algorithm##internal new geometric algorithm"
postMerge: 
  pattern: 
    - "test/algorithms/geometric-test.js"
    - "test/algorithms/new-test.js"
preMerge:
  pattern:
    - "test/algorithms/geometric-test.js"
    - "test/algorithms/new-test.js"
preRun:
     command:
        - npm i
postRun:
     command:
        - node --version
version: 1.0
